repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  # Python code quality tools (via Poetry)
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        language: system
        entry: bash -c 'cd api && poetry run ruff check'
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        language: system
        entry: bash -c 'cd api && poetry run ruff format'
        types_or: [python, pyi]
      - id: pyright
        name: pyright
        language: system
        entry: bash -c 'cd api && poetry run pyright .'
        types_or: [python, pyi]
      - id: markdownlint
        name: markdownlint
        language: system
        entry: markdownlint
        types_or: [markdown]
        args: [--fix]
