apiVersion: 1

# PagerDuty contact points for Grafana unified alerting
contact_points:
  - uid: pagerduty-critical
    name: pagerduty-critical
    type: pagerduty
    settings:
      integrationKey: "${PAGERDUTY_CURRENCY_APP_KEY}"
      severity: "critical"
      component: "currency-api"
      group: "currency-conversion-system"
      summary: "Critical alert from Currency API"
      source: "grafana"
      customDetails:
        service: "currency-api"
        environment: "production"
        dashboard: "http://localhost:3000"
        runbook: "https://your-runbook-url.com"
    disableResolveMessage: false

  - uid: pagerduty-warning
    name: pagerduty-warning
    type: pagerduty
    settings:
      integrationKey: "${PAGERDUTY_CURRENCY_APP_KEY}"
      severity: "warning"
      component: "currency-api"
      group: "currency-conversion-system"
      summary: "Warning alert from Currency API"
      source: "grafana"
      customDetails:
        service: "currency-api"
        environment: "production"
        dashboard: "http://localhost:3000"
        runbook: "https://your-runbook-url.com"
    disableResolveMessage: false

  - uid: pagerduty-load-tester
    name: pagerduty-load-tester
    type: pagerduty
    settings:
      integrationKey: "${PAGERDUTY_LOAD_TESTER_KEY:-${PAGERDUTY_CURRENCY_APP_KEY}}"
      severity: "warning"
      component: "load-tester"
      group: "currency-conversion-system"
      summary: "Load tester alert"
      source: "grafana"
      customDetails:
        service: "load-tester"
        environment: "production"
        dashboard: "http://localhost:3000"
        runbook: "https://your-runbook-url.com"
    disableResolveMessage: false
